name = "PhotonicBandConnectivity"
uuid = "d7bc101a-f969-4292-96d7-1ebdabfa903f"
authors = ["Thomas Christensen <tchr@mit.edu>"]
version = "0.5.1"

[deps]
Crystalline = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LLLplus = "142c1900-a1c3-58ae-a66d-b187f9ca6423"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SymmetryBases = "cb68ded9-7e8c-45d3-bc66-19b5867c0467"

[compat]
DocStringExtensions = "0.8, 0.9"
Crystalline = "0.6.16"
LLLplus = "1.4"
SymmetryBases = "0.5"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
